from typing import Any, Optional, Protocol
from uuid import UUID


class IRepositorioUsuarios(Protocol):
    """Protocolo que define el contrato de acceso a datos para Usuarios."""

    async def obtener_por_id(self, id: UUID) -> Optional[Any]: ...
    async def obtener_por_dni(self, dni: str) -> Optional[Any]: ...
    async def obtener_por_email(self, email: str) -> Optional[Any]: ...
    async def crear(self, usuario: Any) -> Any: ...
    async def actualizar_password(self, id: UUID, nuevo_hash: str) -> bool: ...

