from typing import Any, Protocol


class IRepositorioEnvios(Protocol):
    """Protocolo que define el contrato de acceso a datos para Envíos y Paquetes."""

    async def crear(self, envio: Any) -> Any: ...
    async def obtener_por_token(self, token: str) -> Any | None: ...
    async def existe_token(self, token: str) -> bool: ...
    async def existe_numero_paquete(self, numero_paquete: str) -> bool: ...
