class ErrorCodes:
    AUTH_FAILED = "AUTH_FAILED"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    DUPLICATE_ENTRY = "DUPLICATE_ENTRY"
    PASSWORD_POLICY_ERROR = "PASSWORD_POLICY_ERROR"
    INVALID_TOKEN = "INVALID_TOKEN"
    FORBIDDEN_SCOPE = "FORBIDDEN_SCOPE"
    FORBIDDEN_ACCESS = "FORBIDDEN_ACCESS"
    NOT_FOUND = "NOT_FOUND"
    INTERNAL_ERROR = "INTERNAL_ERROR"

