"""esquema inicial completo HU01-HU13

Revision ID: 5c87e509d4e7
Revises: 
Create Date: 2026-09-02 10:02:10.665499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c87e509d4e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preguntas_frecuentes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('pregunta', sa.String(length=255), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('publicada', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('sucursales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('provincia', sa.String(length=100), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('envios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('remitente_nombre', sa.String(length=150), nullable=False),
    sa.Column('remitente_documento', sa.String(length=20), nullable=False),
    sa.Column('remitente_telefono', sa.String(length=30), nullable=False),
    sa.Column('remitente_email', sa.String(length=150), nullable=False),
    sa.Column('destinatario_nombre', sa.String(length=150), nullable=False),
    sa.Column('destinatario_telefono', sa.String(length=30), nullable=False),
    sa.Column('destinatario_email', sa.String(length=150), nullable=False),
    sa.Column('tipo_entrega', sa.String(length=20), nullable=False),
    sa.Column('provincia_destino', sa.String(length=100), nullable=True),
    sa.Column('ciudad_destino', sa.String(length=100), nullable=True),
    sa.Column('direccion_destino', sa.String(length=255), nullable=True),
    sa.Column('latitud_destino', sa.Float(), nullable=True),
    sa.Column('longitud_destino', sa.Float(), nullable=True),
    sa.Column('sucursal_destino_id', sa.Integer(), nullable=True),
    sa.Column('terminos_aceptados', sa.Boolean(), nullable=False),
    sa.Column('token_seguimiento', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_destino_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_envios_token_seguimiento'), 'envios', ['token_seguimiento'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('requiere_cambio_password', sa.Boolean(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_dni'), 'usuarios', ['dni'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('notificaciones_envio',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('envio_id', sa.Uuid(), nullable=False),
    sa.Column('canal', sa.String(length=10), nullable=False),
    sa.Column('destinatario_tipo', sa.String(length=15), nullable=False),
    sa.Column('destino', sa.String(length=150), nullable=False),
    sa.Column('estado', sa.String(length=15), nullable=False),
    sa.Column('proveedor_mensaje_id', sa.String(length=150), nullable=True),
    sa.Column('error_detalle', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("canal IN ('EMAIL', 'WHATSAPP')", name='ck_notificaciones_envio_canal'),
    sa.CheckConstraint("destinatario_tipo IN ('REMITENTE', 'DESTINATARIO')", name='ck_notificaciones_envio_destinatario_tipo'),
    sa.CheckConstraint("estado IN ('PENDIENTE', 'ENVIADO', 'FALLIDO')", name='ck_notificaciones_envio_estado'),
    sa.ForeignKeyConstraint(['envio_id'], ['envios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_envio_envio_id'), 'notificaciones_envio', ['envio_id'], unique=False)
    op.create_table('paquetes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('envio_id', sa.Uuid(), nullable=False),
    sa.Column('numero_paquete', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=False),
    sa.Column('largo_cm', sa.Float(), nullable=False),
    sa.Column('ancho_cm', sa.Float(), nullable=False),
    sa.Column('alto_cm', sa.Float(), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('sucursal_actual_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['envio_id'], ['envios.id'], ),
    sa.ForeignKeyConstraint(['sucursal_actual_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paquetes_numero_paquete'), 'paquetes', ['numero_paquete'], unique=True)
    op.create_table('repartidores',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('sucursal_base_id', sa.Integer(), nullable=False),
    sa.Column('tipo_reparto', sa.String(length=10), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("tipo_reparto IN ('CORTA', 'LARGA')", name='ck_repartidores_tipo_reparto'),
    sa.ForeignKeyConstraint(['sucursal_base_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('eventos_entrega',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('paquete_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_evento', sa.String(length=20), nullable=False),
    sa.Column('resultado', sa.String(length=10), nullable=False),
    sa.Column('receptor_nombre', sa.String(length=150), nullable=True),
    sa.Column('receptor_documento', sa.String(length=20), nullable=True),
    sa.Column('es_autorizado', sa.Boolean(), nullable=False),
    sa.Column('documento_destinatario_verificado', sa.Boolean(), nullable=False),
    sa.Column('firma_imagen', sa.LargeBinary(), nullable=True),
    sa.Column('firma_content_type', sa.String(length=50), nullable=True),
    sa.Column('motivo_fallo', sa.String(length=255), nullable=True),
    sa.Column('usuario_registro_id', sa.Uuid(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("resultado IN ('EXITOSO', 'FALLIDO')", name='ck_eventos_entrega_resultado'),
    sa.CheckConstraint("tipo_evento IN ('ENTREGA_DOMICILIO', 'RETIRO_SUCURSAL')", name='ck_eventos_entrega_tipo'),
    sa.ForeignKeyConstraint(['paquete_id'], ['paquetes.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['usuario_registro_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_eventos_entrega_paquete', 'eventos_entrega', ['paquete_id', 'created_at'], unique=False)
    op.create_table('historial_estados_paquete',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('paquete_id', sa.Uuid(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=30), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=30), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paquete_id'], ['paquetes.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_historial_estados_paquete_id', 'historial_estados_paquete', ['paquete_id', 'created_at'], unique=False)
    op.create_table('reclamos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('envio_id', sa.Uuid(), nullable=False),
    sa.Column('paquete_id', sa.Uuid(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('contacto_nombre', sa.String(length=150), nullable=False),
    sa.Column('contacto_email', sa.String(length=150), nullable=True),
    sa.Column('contacto_telefono', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.String(length=15), nullable=False),
    sa.Column('resolucion', sa.Text(), nullable=True),
    sa.Column('usuario_resolucion_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado IN ('ABIERTO', 'EN_REVISION', 'RESUELTO', 'RECHAZADO')", name='ck_reclamos_estado'),
    sa.CheckConstraint("tipo IN ('DEMORA', 'DANIO', 'EXTRAVIO', 'OTRO')", name='ck_reclamos_tipo'),
    sa.ForeignKeyConstraint(['envio_id'], ['envios.id'], ),
    sa.ForeignKeyConstraint(['paquete_id'], ['paquetes.id'], ),
    sa.ForeignKeyConstraint(['usuario_resolucion_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reclamos_envio_id'), 'reclamos', ['envio_id'], unique=False)
    op.create_table('recorridos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('repartidor_id', sa.Uuid(), nullable=False),
    sa.Column('sucursal_origen_id', sa.Integer(), nullable=False),
    sa.Column('tipo_distancia', sa.String(length=10), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=15), nullable=False),
    sa.Column('generado_automaticamente', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado IN ('GENERADO', 'EN_EDICION', 'EN_CURSO', 'FINALIZADO')", name='ck_recorridos_estado'),
    sa.CheckConstraint("tipo_distancia IN ('CORTA', 'LARGA')", name='ck_recorridos_tipo_distancia'),
    sa.ForeignKeyConstraint(['repartidor_id'], ['repartidores.usuario_id'], ),
    sa.ForeignKeyConstraint(['sucursal_origen_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertas_recorrido',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('paquete_id', sa.Uuid(), nullable=False),
    sa.Column('recorrido_id', sa.Uuid(), nullable=True),
    sa.Column('motivo', sa.String(length=40), nullable=False),
    sa.Column('resuelta', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resuelta_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paquete_id'], ['paquetes.id'], ),
    sa.ForeignKeyConstraint(['recorrido_id'], ['recorridos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posicion_actual_repartidor',
    sa.Column('repartidor_id', sa.Uuid(), nullable=False),
    sa.Column('recorrido_id', sa.Uuid(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('actualizado_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recorrido_id'], ['recorridos.id'], ),
    sa.ForeignKeyConstraint(['repartidor_id'], ['repartidores.usuario_id'], ),
    sa.PrimaryKeyConstraint('repartidor_id')
    )
    op.create_table('recorrido_paquetes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recorrido_id', sa.Uuid(), nullable=False),
    sa.Column('paquete_id', sa.Uuid(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('estado_en_recorrido', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("estado_en_recorrido IN ('PENDIENTE', 'ENTREGADO', 'FALLIDO')", name='ck_recorrido_paquetes_estado'),
    sa.ForeignKeyConstraint(['paquete_id'], ['paquetes.id'], ),
    sa.ForeignKeyConstraint(['recorrido_id'], ['recorridos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recorrido_id', 'orden', name='uq_recorrido_paquetes_recorrido_orden'),
    sa.UniqueConstraint('recorrido_id', 'paquete_id', name='uq_recorrido_paquetes_recorrido_paquete')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recorrido_paquetes')
    op.drop_table('posicion_actual_repartidor')
    op.drop_table('alertas_recorrido')
    op.drop_table('recorridos')
    op.drop_index(op.f('ix_reclamos_envio_id'), table_name='reclamos')
    op.drop_table('reclamos')
    op.drop_index('idx_historial_estados_paquete_id', table_name='historial_estados_paquete')
    op.drop_table('historial_estados_paquete')
    op.drop_index('idx_eventos_entrega_paquete', table_name='eventos_entrega')
    op.drop_table('eventos_entrega')
    op.drop_table('repartidores')
    op.drop_index(op.f('ix_paquetes_numero_paquete'), table_name='paquetes')
    op.drop_table('paquetes')
    op.drop_index(op.f('ix_notificaciones_envio_envio_id'), table_name='notificaciones_envio')
    op.drop_table('notificaciones_envio')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_dni'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_envios_token_seguimiento'), table_name='envios')
    op.drop_table('envios')
    op.drop_table('sucursales')
    op.drop_table('roles')
    op.drop_table('preguntas_frecuentes')
    # ### end Alembic commands ###

